### ISSUE TITLE
Take some code from the CF in swift-corelibs-foundation

### ISSUE THREAD

**Issue by Artoria2e5** [gnustep/corebase#11]
To make sure their Swift language does not depend on an OC environment on non-Apple platforms, Apple has made a Swift version of the Foundation Kit available under Apache License v2.0. Their Foundation contains a [Core Foundation implementation](https://github.com/apple/swift-corelibs-foundation/tree/master/CoreFoundation) that is similar to the CFLite they released on opensource.apple.com, but is better organized and more complete.

Since the Swift CF is under a GPL-compatible license now, it might make some sense to take some code from it to fill up what CoreBase is missing in. There isn't a table of implementation progress to rely on, but it seems that the parts around binary property lists can definity use some Apple code.

**Comment by stefanbidi** [comment]
There are a few problems with what you are proposing.

GNUstep, as the name suggests, is a GNU project and requires contributors to sign a copyright assignment to the FSF.

Additionally, while the Apache v2.0 is compatible with GPL and LGPL v3, it is not compatible with LGPLv2.1, used by CoreBase. See [Various Licenses and Comments about Them](https://www.gnu.org/licenses/license-list.en.html) for additional information.
