### ISSUE TITLE
icu-config is deprecated

### ISSUE THREAD

**Issue by cburgmer** [gnustep/corebase#14]
It is now advised to use pkg-config: http://userguide.icu-project.org/howtouseicu.

I also seems that it hasn't been shipped in Ubuntu since "disco": https://packages.ubuntu.com/search?suite=disco&arch=any&mode=exactfilename&searchon=contents&keywords=icu-config and thus this package fails to build on Ubuntu.

**Comment by cburgmer** [comment]
Using version e606d29699d6f8b72f9ae050db60ce3f5ecb4806 solves my problem, so a new release should fix this issue.

**Comment by stefanbidi** [comment]
Corebase has not had a release in many years. There are still a few outstanding problems that need to be addressed before a release is made. Hopefully, I can get some time to fix everything I want soon so that another release can be made.
