### ISSUE TITLE
Unable to build ./configure without ICU

### ISSUE THREAD

**Issue by cburgmer** [gnustep/corebase#15]
Running configure fails on newer Ubuntu because of #14. 
The output suggests `Please install ICU or specify --without-icu` but running configure with the switch produces `configure: WARNING: unrecognized options: --without-icu`. 
Am I reading the suggestions wrong?

**Comment by stefanbidi** [comment]
That's very strange. The configure script has the option included and specifying --without-icu should not result in a configure error.

Keep in mind that, despite the its availability, this option not officially supported, yet. This is on the to-do list of things I'd like to do before the next release. ICU is used for everything almost everything inside ICU. Significant portions of the library will not work without this library. A few areas, off the top of my head, are: String normalization, data and number formatting, and calendar/time calculations.

Ubuntu includes ICU, so you should install libicu-dev and include the dependency. The library is installed by default, so you won't be adding anything new.

**Comment by stefanbidi** [comment]
I believe this issue was fixed with a previous update to configure. I'm closing it for now since there hasn't been any updates in 2 years.
