### ISSUE TITLE
Unable to find ICU headers

### ISSUE THREAD

**Issue by adderthorn** [gnustep/corebase#21]
the corebase package refuses to configure on FreeBSD failing to find the ICU libraries I know exist. I can't seem to find a way to get `./configure` to see them.

Environment: FreeBSD 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

```
checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... (cached) none needed
checking for gcc... no
checking for objcc... no
checking for objc... no
checking for cc... cc
checking whether we are using the GNU Objective C compiler... yes
checking whether cc accepts -g... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for inline... inline
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of void *... 8
checking for data model... LP64
checking size of double... 8
checking size of long double... 16
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ICU... yes
checking unicode/ucal.h usability... no
checking unicode/ucal.h presence... no
checking for unicode/ucal.h... no
configure: error: Could not find required ICU headers.
```

The headers are located at `/usr/local/include/unicode`

I have tried manually setting the flags:

```
export ICU_CFLAGS=/usr/local/include/
export ICU_LIBS=/usr/local/lib/
```

But that is not working either. Is there something I can do to force configure to see the libraries? I tried looking at the configure file, but I'm not really an expert there and can't seem to understand what it's doing when searching for these ICU headers.

**Comment by stefanbidi** [comment]
The CoreBase library only supports the CFLAGS and LIBS variables directly and does not use the ICU_ prefix. Additionally, you did not properly specify those variables. Try:

    export CFLAGS="-I/usr/local/include"
    export LIBS="-l/usr/local/lib"

You must include the `-I` and `-l` as these flags are passed directly to the c compiler and linker, respectively.

What's interesting is that the PKG_CHECK_MODULES function is not automatically adding these for you. Can you provide a copy of your config.log, as well?

**Comment by adderthorn** [comment]
Thanks for the help. exporting the flags as you suggest did work (with one correction on `-L` instead of `-l` for the `LIBS`). If the ICU flags don't work the config help might need to be altered as running `./configure --help` does show these options:

```
Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  LIBS        libraries to pass to the linker, e.g. -l<library>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CPP         C preprocessor
  OBJC        Objective C compiler command
  OBJCFLAGS   Objective C compiler flags
  PKG_CONFIG  path to pkg-config utility
  PKG_CONFIG_PATH
              directories to add to pkg-config's search path
  PKG_CONFIG_LIBDIR
              path overriding pkg-config's built-in search path
  ICU_CFLAGS  C compiler flags for ICU, overriding pkg-config
  ICU_LIBS    linker flags for ICU, overriding pkg-config
```

I have attached the config.log from running without setting the flags as you asked for. It does look like it finds pkg-config but it is not getting the paths from it.

[config.log](https://github.com/gnustep/libs-corebase/files/9226459/config.log)

**Comment by stefanbidi** [comment]
I looked into this a little further and it seems that the PKG_CHECK_MODULES() function in configure adds ICU_CFLAGS and ICU_LIBS. The problem, it would seem, is that it does not actually allows those variables to be overridden, as stated in the help. Since we have a workaround (specifying CFLAGS and LIBS) and this is not a problem in CoreBase, I'm going to close this issue.

**Comment by triplef** [comment]
I’ve had the same issue when building CoreBase where I had to manually specify CFLAGS to find ICU, even though building Base with ICU worked without this:
https://github.com/gnustep/tools-android/blob/27953e9abd1510704bdb2562d513611e920ec8b9/phases/40-gnustep-corebase.sh#L21-L26

I’m guessing that Base uses existing flags from tools-make but CoreBase does not when finding ICU? I’m sure it would be helpful if someone could figure this out.

**Comment by stefanbidi** [comment]
I believe I found the issue. Since ICU_CFLAGS and ICU_LIBS are defined by PKG_CHECK_MODULES, but not used by the rest of the configure script.

**Comment by triplef** [comment]
Thanks @stefanbidi! This works now, though I’m getting the following warnings which I didn’t get before:

```
checking for icu-i18n > 49.0... yes
checking unicode/ucal.h usability... yes
checking unicode/ucal.h presence... no
configure: WARNING: unicode/ucal.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: unicode/ucal.h: proceeding with the compiler's result
checking for unicode/ucal.h... yes
```

Here’s the relevant part from config.log, looks like the include path is missing for the presence check for some reason:
```
configure:5049: checking for icu-i18n > 49.0
configure:5056: $PKG_CONFIG --exists --print-errors "icu-i18n > 49.0"
configure:5059: $? = 0
configure:5073: $PKG_CONFIG --exists --print-errors "icu-i18n > 49.0"
configure:5076: $? = 0
configure:5134: result: yes
configure:5141: checking unicode/ucal.h usability
configure:5141: /Users/frederik/Library/Android/sdk/ndk/25.1.8937393//toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android23-clang -c -fstack-protector-strong -D_FORTIFY_SOURCE=2 -I/Users/frederik/Library/Android/GNUstep/x86_64/include  conftest.c >&5
configure:5141: $? = 0
configure:5141: result: yes
configure:5141: checking unicode/ucal.h presence
configure:5141: /Users/frederik/Library/Android/sdk/ndk/25.1.8937393//toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android23-clang -E  conftest.c
conftest.c:28:10: fatal error: 'unicode/ucal.h' file not found
#include <unicode/ucal.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
configure:5141: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libgnustep-corebase"
| #define PACKAGE_TARNAME "libgnustep-corebase"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "libgnustep-corebase 0.2"
| #define PACKAGE_BUGREPORT "bug-gnustep@gnu.org"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIZEOF_CHAR 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_VOID_P 8
| #define DATA_MODEL DATA_MODEL_LP64
| #define SIZEOF_DOUBLE 8
| #define SIZEOF_LONG_DOUBLE 16
| /* end confdefs.h.  */
| #include <unicode/ucal.h>
configure:5141: result: no
configure:5141: WARNING: unicode/ucal.h: accepted by the compiler, rejected by the preprocessor!
configure:5141: WARNING: unicode/ucal.h: proceeding with the compiler's result
configure:5141: checking for unicode/ucal.h
configure:5141: result: yes
```

**Comment by stefanbidi** [comment]
Can you attach a copy of config.log? Hopefully that'll include more
information.

**Comment by triplef** [comment]
Sure, here you go: [config.log](https://github.com/gnustep/libs-corebase/files/9557649/config.log)

**Comment by stefanbidi** [comment]
Could you also get me a copy of your GNUstep-base config.log? I'd like to know how CPPFLAGS and CFLAGS are handled there and that will be the best way to do it. I had a look at the base configure.ac script, but it's quite long and I got confused.

**Comment by triplef** [comment]
Sure, here’s the one from Base: [config.log](https://github.com/gnustep/libs-corebase/files/9558658/config.log)
